"""Markdown reporter — turns an `InvestigationReport` into Confluence-ready MD."""

from __future__ import annotations

import logging
from pathlib import Path

from seo_agent.config import ensure_reports_dir
from seo_agent.models.investigation import InvestigationReport, Severity
from seo_agent.utils.formatters import (
    SEVERITY_ICON,
    format_findings_grouped,
    md_table,
)

logger = logging.getLogger(__name__)


class MarkdownReporter:
    """Render an `InvestigationReport` to Markdown and optionally persist it."""

    def render(self, report: InvestigationReport) -> str:
        lines: list[str] = []
        lines.append(f"# SEO Incident Investigation — {report.hostname}")
        lines.append("")
        lines.append(
            f"**Market:** {report.market} &nbsp;•&nbsp; "
            f"**Period:** {report.period_start} → {report.period_end} &nbsp;•&nbsp; "
            f"**Generated:** {report.generated_at.isoformat(timespec='minutes')}"
        )
        lines.append("")

        # Executive summary
        lines.append("## Executive summary")
        lines.append(report.executive_summary or "_No summary generated._")
        lines.append("")

        # Module status table
        lines.append("## Module status")
        lines.append(
            md_table(
                ["Module", "Status", "Findings", "Message"],
                [
                    [m.module, m.status, len(m.findings), m.message or ""]
                    for m in report.modules
                ],
            )
        )
        lines.append("")

        # Severity breakdown
        lines.append("## Severity breakdown")
        counts = {
            s: len(report.findings_by_severity(s))
            for s in (
                Severity.CRITICAL,
                Severity.HIGH,
                Severity.MEDIUM,
                Severity.LOW,
                Severity.INFO,
            )
        }
        lines.append(
            md_table(
                ["Severity", "Count"],
                [
                    [f"{SEVERITY_ICON[s]} {s.value}", c]
                    for s, c in counts.items()
                ],
            )
        )
        lines.append("")

        # Per-module findings
        lines.append("## Findings")
        for m in report.modules:
            lines.append(f"### Module: `{m.module}` ({m.status})")
            if not m.findings:
                lines.append("_No findings._")
            else:
                lines.append(format_findings_grouped(m.findings))
            lines.append("")

        # Recommendations
        lines.append("## Recommendations")
        if not report.recommendations:
            lines.append("_No recommendations._")
        else:
            for i, rec in enumerate(report.recommendations, 1):
                lines.append(
                    f"{i}. {SEVERITY_ICON[rec.priority]} **{rec.title}** — "
                    f"{rec.rationale} _(owner: {rec.owner or 'TBD'})_"
                )
        lines.append("")

        # Footer / data-source map
        lines.append("---")
        lines.append(
            "_Generated by seo-agent. Data sources: Redash · GSC · Jira · Server logs · "
            "SSR probes · External (Google Search Status, SEMRush, DataForSEO)._"
        )
        return "\n".join(lines)

    def save(self, report: InvestigationReport, path: Path | None = None) -> Path:
        reports_dir = ensure_reports_dir() / report.domain
        reports_dir.mkdir(parents=True, exist_ok=True)
        ts = report.generated_at.strftime("%Y%m%d-%H%M%S")
        out = path or reports_dir / f"{report.period_start}_{report.period_end}_{ts}.md"
        out.write_text(self.render(report), encoding="utf-8")
        logger.info("Report written to %s", out)
        return out
